### ISSUE TITLE
#define S(y)	Upp::String(y)  seem like a really bad idea Functions4U/Functions4U.h:1169

### ISSUE THREAD

**Issue by mirek-fidler** [anboto/Functions4U#2]
It just broke my project:

Nord2000::FresnelZone::FresnelZone(Pointf S, Pointf R, Pointf A1, Pointf A2, double Fl)
:	S(S), R(R), A1(A1), A2(A2), Fl(Fl)
{
	Compute();
}

Single letter macro, really? :)

**Comment by izabala123** [comment]
Yes. Not very sophisticated, is it?
`#define S(y)	Upp::String(y)`
This macro is very comfortable to convert a "text" in a Upp::String, in a more compact way than adding String("text").
However it is not documented. If you propose a nice replacement, it would be included immediately.

**Comment by mirek-fidler** [comment]
I think it is a bad taste to force this on every user of the public library.

However, if you really MUST, what about

inline String S(const char *s) { return s; }

Does the same, but at least does not preclude using S as local (variable)
name.

Mirek

**Comment by izabala123** [comment]
Hi Mirek

No problem. Remember that for doing S() I was inspired in t_(), that in U++ is implemented like this:
`#define t_(x)          t_GetLngString(x)`
Anyway I will set now your advice.

Iñaki

**Comment by izabala123** [comment]
It is now uploaded. Please check. Thank you.

**Comment by mirek-fidler** [comment]
Yeah, t_ is a mistake too... but at least it is 2 characters.

**Comment by mirek-fidler** [comment]
Thanks, works fine now. Just a little comment:

String S(const Value &v);

You can convert Value to String by ~ (~v).

Mirek

**Comment by izabala123** [comment]
> String S(const Value &v);
You can convert Value to String by ~ (~v).

Oh yes. However `String S(const Value &v);` is more comfortable as the programmer doesn't have to take care of that.
