### ISSUE TITLE
Does not compile in Linux

### ISSUE THREAD

**Issue by mirek-fidler** [anboto/Functions4U#3]
static void GetInstalledSoftwareDpkg(Array<SoftwareDetails> &ret) {
	String str = Sys("dpkg --list --no-pager");
	StringStream stream(str);
	
	int idname = -1, idver, idarch, iddesc;
	while (!stream.IsEof()) {
		String line = stream.GetLine();
		if ((iddesc = line.Find("Description")) >= 0) {
			idname = line.Find("Name");
			idver = line.Find("Version");
			idarch = line.Find("Architecture");
			break;
		}
	}
	if (idname == -1)
		return;
	
	stream.GetLine();
	LineParser p;
	while (!stream.IsEof()) {	
		p.LoadFields(stream.GetLine(), {idname, idver, idarch, iddesc});

		SoftwareDetails &r = ret.Add();
		r.name = p.GetText(0);	
		r.version = p.GetText(1);
		r.architecture = p.GetInt(2); <<<<<< GetInt instead of GetText
		r.description = p.GetText(3);
		
		// GetSoftwarePath(r);
	}
}

**Comment by izabala123** [comment]
Hopefully fixed. Thank you!
